version: '3.0'

services:
  api:
    depends_on:
      - db
      - cache
    build:
      context: .
    ports:
      - "127.0.0.1:3001:8000"
    env_file:
      - .env.docker
    restart: always
    container_name: qms-tradingdesk-server-api
  cache:
    image: redis
    restart: always
    container_name: qms-tradingdesk-server-cache
    ports:
      - "6379:6379"
  db:
    image: postgres:11.0-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: qms-tradingdesk-server-db
volumes:
  postgres-volume:
