'use strict'

const auth = require('./auth')
const adminUsers = require('./admin/users')
const languages = require('./languages')
const countries = require('./countries')
const regions = require('./regions')
const timezones = require('./timezones')
const roles = require('./roles')
const users = require('./users')
const codes = require('./codes')
const brandCategories = require('./brandCategories')
const assets = require('./assets')
const assetTypes = require('./assetTypes')
const clubs = require('./clubs')
const venues = require('./venues')
const packages = require('./packages')
const KoaRouter = require('koa-router')
const authenticationRequired = require('../middlewares/authenticationRequired')
const mustBeAdmin = require('../middlewares/mustBeAdmin')
const requestHandling = require('../middlewares/requestHandling')
const thirdPartyAuthenticationRequire = require('../middlewares/thirdPartyAuthentication')
const adminRoutes = new KoaRouter({ prefix: '/admin' })
const authenicationRequiredRoutes = new KoaRouter()
const thirdPartyAPI = new KoaRouter()
const ctxFunctions = require('../middlewares/functions')
const codeTypes = require('./codeTypes')
const brands = require('./brands')
const events = require('./events')
const assetUnits = require('./assetUnits')

// Admin Management
const adminCodes = require('./admin/codes')
const adminVenues = require('./admin/venues')
const adminAssetTypes = require('./admin/assetTypes')
const adminBrandCategories = require('./admin/brandCategories')
const adminAssets = require('./admin/assets')
const adminExclusions = require('./admin/exclusions')
const adminAssetUnits = require('./admin/assetUnits')
const adminBrands = require('./admin/brands')
const adminEvents = require('./admin/events')
const adminClubs = require('./admin/clubs')
const adminCodeTypes = require('./admin/codeTypes')
const thirdPartyApp = require('./admin/thirdPartyApp')
const qlikConnection = require('./qlik/qlik')

module.exports = (app) => {
  app.use(requestHandling)

  thirdPartyAPI.use(thirdPartyAuthenticationRequire)
  thirdPartyAPI.use(qlikConnection().routes())

  adminRoutes.use(authenticationRequired)
  adminRoutes.use(mustBeAdmin)
  adminRoutes.use(adminUsers().routes())
  adminRoutes.use(adminAssetUnits().routes())
  adminRoutes.use(adminCodes().routes())
  adminRoutes.use(adminVenues().routes())
  adminRoutes.use(adminAssetTypes().routes())
  adminRoutes.use(adminBrandCategories().routes())
  adminRoutes.use(adminExclusions().routes())
  adminRoutes.use(adminAssets().routes())
  adminRoutes.use(adminBrands().routes())
  adminRoutes.use(adminEvents().routes())
  adminRoutes.use(adminClubs().routes())
  adminRoutes.use(adminCodeTypes().routes())
  adminRoutes.use(thirdPartyApp().routes())

  authenicationRequiredRoutes.use(authenticationRequired)
  authenicationRequiredRoutes.use(languages().routes())
  authenicationRequiredRoutes.use(countries().routes())
  authenicationRequiredRoutes.use(regions().routes())
  authenicationRequiredRoutes.use(timezones().routes())
  authenicationRequiredRoutes.use(roles().routes())
  authenicationRequiredRoutes.use(users().routes())
  authenicationRequiredRoutes.use(codes().routes())
  authenicationRequiredRoutes.use(codeTypes().routes())
  authenicationRequiredRoutes.use(brandCategories().routes())
  authenicationRequiredRoutes.use(assets().routes())
  authenicationRequiredRoutes.use(assetTypes().routes())
  authenicationRequiredRoutes.use(clubs().routes())
  authenicationRequiredRoutes.use(venues().routes())
  authenicationRequiredRoutes.use(packages().routes())
  authenicationRequiredRoutes.use(brands().routes())
  authenicationRequiredRoutes.use(events().routes())
  authenicationRequiredRoutes.use(assetUnits().routes())

  app.use(ctxFunctions)
  app.use(adminRoutes.routes())
  app.use(authenicationRequiredRoutes.routes())
  app.use(thirdPartyAPI.routes())
  app.use(auth().routes())
}
